# Conexion a nuestra base de datos en postgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_springboot_dev
spring.datasource.username=postgres
spring.datasource.password=198115

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de Hibernate
# Usamos 'validate' porque tu tabla ya existe con datos
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect